const icons={
folder:'M3 7h6l2-3h5l2 3h3v13H3z M3 9h18',save:'M4 3h13l4 4v14H3V3z M7 3v6h10V3 M7 21v-8h10v8',info:'M12 11v6 M12 7h.01 <circle cx="12" cy="12" r="9"/>',undo:'M8 4 3 9l5 5 M3 9h10a7 7 0 0 1 7 7v3',redo:'m16 4 5 5-5 5 M21 9H11a7 7 0 0 0-7 7v3',left:'M4 5h16 M4 10h10 M4 15h16 M4 20h10',center:'M4 5h16 M7 10h10 M4 15h16 M7 20h10',right:'M4 5h16 M10 10h10 M4 15h16 M10 20h10',justify:'M4 5h16 M4 10h16 M4 15h16 M4 20h16',list:'M9 5h12 M9 12h12 M9 19h12 M3 5h.01 M3 12h.01 M3 19h.01',number:'M9 5h12 M9 12h12 M9 19h12 M3 3v5 M2 12q3-3 3 0l-3 3h3 M2 18h3l-2 2h2l-3 2',indent:'M3 4h18 M11 9h10 M11 15h10 M3 21h18 M3 9l4 3-4 3',outdent:'M3 4h18 M11 9h10 M11 15h10 M3 21h18 M7 9l-4 3 4 3',eraser:'m14 3 7 7-10 11H7l-5-5z M7 11l7 7 M12 21h9',search:'M15.5 15.5 21 21 <circle cx="10" cy="10" r="7"/>',copy:'M9 3h12v14H9z M5 7H3v14h12v-2',delete:'M3 6h18 M9 6V3h6v3 M5 6l1 15h12l1-15 M9 10v7 M15 10v7',monitor:'M3 3h18v13H3z M8 21h8 M12 16v5',tablet:'M5 2h14v20H5z M11 19h2',mobile:'M7 2h10v20H7z M11 19h2',image:'M3 3h18v18H3z M3 17l6-6 4 4 3-3 5 5 <circle cx="16" cy="7" r="1.5"/>',table:'M3 3h18v18H3z M3 9h18 M3 15h18 M9 3v18 M15 3v18',link:'m10 14 4-4 M8 16l-2 2a4 4 0 0 1-5-5l5-5a4 4 0 0 1 5 0 M13 16a4 4 0 0 0 5 0l5-5a4 4 0 0 0-5-5l-2 2',rule:'M3 12h18 M5 7h14 M5 17h14',heading:'M5 4v16 M19 4v16 M5 12h14',text:'M4 5h16 M12 5v15 M8 20h8',section:'M3 3h18v18H3z M3 8h18 M9 8v13',outline:'M3 5h18 M3 12h3 M10 12h11 M3 19h3 M10 19h11',code:'m8 6-6 6 6 6 M16 6l6 6-6 6 M14 3l-4 18',minus:'M5 12h14',plus:'M5 12h14 M12 5v14',actual:'M4 8v8 M3 9l1-1 M10 8v8 M9 9l1-1 M15 8h5v8h-5z',home:'m3 10 9-8 9 8 M5 8v13h14V8 M9 21v-7h6v7',back:'m10 4-8 8 8 8 M2 12h20',chevron:'m9 5 7 7-7 7',document:'M5 2h9l5 5v15H5z M14 2v6h5 M8 12h8 M8 16h8',close:'m6 6 12 12 M6 18 18 6'
};
function renderIcons(root=document){root.querySelectorAll('i[data-icon]').forEach(el=>{const raw=icons[el.dataset.icon]||icons.document;const index=raw.indexOf('<');el.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="'+(index<0?raw:raw.slice(0,index))+'"/>'+(index<0?'':raw.slice(index))+'</svg>';});}
renderIcons();
let zoom=100,outlineTimer,showOutline=true;
function setTab(tab){document.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===tab);b.setAttribute('aria-selected',String(b.dataset.tab===tab));});document.querySelectorAll('[data-page]').forEach(p=>p.hidden=p.dataset.page!==tab);}
function showHome(){if(busy)return;$('welcome').hidden=false;$('workspace').hidden=true;$('ribbon').hidden=true;$('zoom-controls').hidden=true;document.body.classList.add('backstage');$('return-document').hidden=!file;refreshRecent();}
function returnDocument(){if(!file)return;updateFile();}
async function refreshRecent(){try{const rows=await result(np.recent());const host=$('recent-list');host.replaceChildren();$('recent-empty').hidden=rows.length>0;$('clear-recent').disabled=rows.length===0;rows.forEach(row=>{const button=document.createElement('button');button.className='recent-row';button.title=row.path;const icon=document.createElement('i');icon.dataset.icon='document';const name=document.createElement('span');name.className='recent-name';const strong=document.createElement('strong');strong.textContent=row.name;const small=document.createElement('small');small.textContent=row.path;name.append(strong,small);const date=document.createElement('span');date.className='recent-date';date.textContent=new Date(row.opened).toLocaleDateString('ko-KR');button.append(icon,name,date);button.onclick=()=>open(row.path);host.append(button);});renderIcons(host);}catch(e){toast(e.message,true);}}
window.refreshRecent=refreshRecent;
function command(cmd,value){if(!ready||busy||mode!=='tiny')return;editor.focus();editor.execCommand(cmd,false,value);changed();updateFormatting();}
function updateFormatting(){if(!ready||mode!=='tiny')return;document.querySelectorAll('[data-command]').forEach(b=>{if(['Indent','Outdent','RemoveFormat'].includes(b.dataset.command))return;try{b.setAttribute('aria-pressed',String(editor.queryCommandState(b.dataset.command)));}catch{}});for(const [id,cmd]of [['font-family','FontName'],['font-size','FontSize']]){const el=$(id);let value=editor.queryCommandValue(cmd)||'';value=String(value).replace(/["']/g,'');el.querySelector('[data-current]')?.remove();let option=[...el.options].find(o=>o.value.toLowerCase()===value.toLowerCase());if(!option&&value){option=document.createElement('option');option.value=value;option.textContent=value;option.dataset.current='';el.append(option);}el.value=option?option.value:'';}}
function setZoom(value){zoom=Math.max(50,Math.min(150,Number(value)));$('zoom-range').value=zoom;$('zoom-label').textContent=zoom+'%';if(!ready)return;if(mode==='tiny')editor.getDoc().documentElement.style.zoom=zoom/100;else editor.Canvas.setZoom(zoom);}
function updateOutline(){if(!ready)return;const doc=mode==='tiny'?editor.getDoc():editor.Canvas.getDocument();const text=doc.body.innerText.trim();$('document-stats').textContent=text.length.toLocaleString('ko-KR')+'자';const host=$('outline-list');host.replaceChildren();const headings=[...doc.querySelectorAll('h1,h2,h3')].filter(el=>el.textContent.trim());if(!headings.length){const empty=document.createElement('div');empty.className='empty';empty.textContent='제목 스타일을 적용하면 문서 목차가 표시됩니다.';host.append(empty);}for(const heading of headings){const b=document.createElement('button');b.textContent=heading.textContent.trim();b.title=b.textContent;b.className='level-'+heading.tagName.slice(1);b.onclick=()=>{heading.scrollIntoView({behavior:'smooth',block:'start'});host.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));if(mode==='tiny'){editor.selection.select(heading,true);editor.selection.collapse(true);editor.focus();}};host.append(b);}}
window.scheduleOutline=()=>{clearTimeout(outlineTimer);outlineTimer=setTimeout(updateOutline,400);};
window.editorReady=()=>{document.body.classList.toggle('design-mode',mode==='grapes');setZoom(zoom);updateOutline();if(mode==='tiny'){editor.on('NodeChange SelectionChange',updateFormatting);updateFormatting();}renderIcons();};
const tableHTML='<table style="width:100%;border-collapse:collapse"><tbody><tr><th style="border:1px solid #cbd5e1;padding:10px">항목</th><th style="border:1px solid #cbd5e1;padding:10px">내용</th></tr><tr><td style="border:1px solid #cbd5e1;padding:10px">항목</td><td style="border:1px solid #cbd5e1;padding:10px">내용</td></tr></tbody></table>';
async function action(name){if(!ready||busy)return;try{switch(name){case'undo':if(mode==='tiny')editor.undoManager.undo();else editor.UndoManager.undo();changed();break;case'redo':if(mode==='tiny')editor.undoManager.redo();else editor.UndoManager.redo();changed();break;case'image':await insertImage();break;case'table':if(mode==='tiny')command('mceInsertTable',{rows:3,columns:3});else{editor.getWrapper().append(tableHTML);changed();}break;case'link':command('mceLink');break;case'rule':command('InsertHorizontalRule');break;case'search':command('SearchReplace');break;case'code':command('mceCodeEditor');break;case'visualblocks':command('mceVisualBlocks');break;case'outline':showOutline=!showOutline;$('outline-panel').hidden=!showOutline;break;case'folder':await np.reveal();break;case'zoom-in':setZoom(zoom+10);break;case'zoom-out':setZoom(zoom-10);break;case'zoom-reset':setZoom(100);break;case'duplicate':{const selected=editor.getSelected();if(selected&&selected!==editor.getWrapper()){const parent=selected.parent();parent.append(selected.clone(),{at:parent.components().indexOf(selected)+1});changed();}else toast('복제할 요소를 먼저 선택하세요.');break;}case'delete':{const selected=editor.getSelected();if(selected&&selected!==editor.getWrapper()){selected.remove();changed();}else toast('삭제할 요소를 먼저 선택하세요.');break;}case'device-desktop':editor.setDevice('데스크톱');break;case'device-tablet':editor.setDevice('태블릿');break;case'device-mobile':editor.setDevice('모바일');break;case'add-heading':editor.getWrapper().append('<h2>새 제목</h2>');changed();break;case'add-text':editor.getWrapper().append('<p>새 내용을 입력하세요.</p>');changed();break;case'add-section':editor.getWrapper().append('<section style="padding:24px"><h2>새 구역</h2><p>내용을 입력하세요.</p></section>');changed();break;}}catch(e){toast(e.message,true);}}
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));
document.querySelectorAll('[data-command]').forEach(b=>b.onclick=()=>command(b.dataset.command));
document.querySelectorAll('[data-format]').forEach(b=>b.onclick=()=>command('FormatBlock',b.dataset.format));
document.querySelectorAll('#ribbon button').forEach(b=>b.addEventListener('mousedown',event=>event.preventDefault()));
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{if(file){returnDocument();setTab(b.dataset.tab);}});
$('font-family').onchange=event=>command('FontName',event.target.value);
$('font-size').onchange=event=>command('FontSize',event.target.value);
$('text-color').oninput=event=>command('ForeColor',event.target.value);
$('highlight-color').oninput=event=>command('HiliteColor',event.target.value);
$('zoom-range').oninput=event=>setZoom(event.target.value);
$('file-tab').onclick=()=>document.body.classList.contains('backstage')&&file?returnDocument():showHome();
$('return-document').onclick=returnDocument;$('nav-open').onclick=()=>open();$('home-menu').onclick=showHome;
$('close-outline').onclick=()=>{showOutline=false;$('outline-panel').hidden=true;};
$('clear-recent').onclick=async()=>{try{await result(np.clearRecent());await refreshRecent();}catch(e){toast(e.message,true);}};
// The recent list is local to this installation; clearing it never deletes documents.
showHome();uiBusy(false);

if(np.platform==='darwin'){
  document.querySelector('.home-nav-bottom small').textContent='버전 1.1.0 · macOS';
  document.querySelector('#welcome-open strong').textContent='내 Mac에서 열기';
  document.querySelectorAll('[title]').forEach(el=>el.title=el.title.replaceAll('Ctrl+','⌘'));
  const font=$('font-family').querySelector('option[value="맑은 고딕"]');font.value='Apple SD Gothic Neo';font.textContent='Apple SD Gothic Neo';
  new MutationObserver(()=>{const el=$('footer-status');if(el.textContent.includes('Ctrl+'))el.textContent=el.textContent.replaceAll('Ctrl+','⌘');}).observe($('footer-status'),{childList:true,characterData:true,subtree:true});
}
np.onMenu(command=>{if(command==='open')open();else if(command==='save')save();else if(command==='save-as')save(true);else action(command);});
